#!/bin/bash

VER=1.1.2.0

docker build -t dconnolly/bitcoin-cash:latest -t dconnolly/bitcoin-cash:unlimited -t dconnolly/bitcoin-cash:unlimited-$VER .

docker push dconnolly/bitcoin-cash:latest
docker push dconnolly/bitcoin-cash:unlimited
docker push dconnolly/bitcoin-cash:unlimited-$VER

